### ISSUE TITLE
Add scoring system

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#1]

**Comment by Aniq55** [comment]
The scoring system is there, but ill-defined. It just needs to be displayed on the screen.
@falconis shall I assign this to you?

**Comment by vineetjc** [comment]
If not assigned yet, if you'd like, I would like to work on this.

**Comment by pani-vishal** [comment]
Sure I would happily work on it! @Aniq55

**Comment by Aniq55** [comment]
I'm closing this issue as #18 covers this.
