### ISSUE TITLE
Add a background music track which plays on loop

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#11]

**Comment by vineetjc** [comment]
I wish to work on this. It would be great if I am assigned to solving this issue.

**Comment by arpitmisraw** [comment]
I would also like to work on this.

**Comment by nebula001** [comment]
I would like to work on this .

**Comment by Aniq55** [comment]
Assigned to @thealphadollar

**Comment by thealphadollar** [comment]
@Aniq55 Please ask the assignee to post update on this, it's been 11 days.
Also, play different music in menu and different when the actual game starts.

**Comment by thealphadollar** [comment]
Do I have the permission to work on this?

**Comment by Aniq55** [comment]
@thealphadollar reassigned to you.
