### ISSUE TITLE
Have a set of music files as background music.

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#114]
Have a set of music files which play randomly after one finishes.

**Comment by nityanandagohain** [comment]
so  i will be working on this

**Comment by Aniq55** [comment]
Why?

**Comment by thealphadollar** [comment]
@Aniq55 By mistake I wrote songs, I meant we can have multiple tunes as background and they can be shuffled by the press of a button or when the previous sound ends; just addition of a feature.

**Comment by Aniq55** [comment]
There maybe copyright issues. And I hope the current tracks are free. If not please check that first. @thealphadollar

**Comment by thealphadollar** [comment]
@Aniq55  Yes, I've verified the current music files have been taken from websites providing files under open source agreement for use in projects. No issues on that side.
