### ISSUE TITLE
Multiple Theme choice

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#115]
From the start screen allow the player to select a theme for the base of the playing field.  Friction on the field should vary according to the theme chosen (example ice should have a low value of friction).

**Comment by nityanandagohain** [comment]
I dont think start screen has enough space for multiple image choice . I think a new screen should be created after start screen.

**Comment by thealphadollar** [comment]
@nityanandagohain Yup, go with a new screen with at most six choices for the theme and read the updated initial comment.
