### ISSUE TITLE
Make paddles a circle instead of a bar

### ISSUE THREAD

**Issue by abh3po** [NITDgpOS/AirHockey#13]
Like the actual air hockey

**Comment by Aniq55** [comment]
when two circle collide head-on, they would be reflected along the same line of action. That would make the game less chaotic

**Comment by abh3po** [comment]
Imagine both moving in different directions? Also it's more true to the
real game if it's a circle isn't it?

**Comment by Aniq55** [comment]
Okay. Then we will also need to add goals, to make the game more realistic.

**Comment by Aniq55** [comment]
Issue #16 already takes care of this
