### ISSUE TITLE
Program hangs in puck.py

### ISSUE THREAD

**Issue by ghost** [NITDgpOS/AirHockey#131]
The program hangs in collidesWithPaddle function of puck.py after selecting 'Easy' or 'Hard' mode using keyboard

**Comment by vineetjc** [comment]
Is this still an issue? @kishore-saldanha I don't seem to be facing any such problem, but I'm not sure if I understood you right.

**Comment by vineetjc** [comment]
@kishore-saldanha - Correct me if I'm wrong: I selected game difficulty using the keyboard, and according to this, I should be expecting the program to hang? I believe this isn't the case anymore. Please check this out; this might be irrelevant now so that we can close it.

**Comment by ghost** [comment]
It is solved . The older version of code had the bug

**Comment by vineetjc** [comment]
@Aniq55 We can close this issue

**Comment by thealphadollar** [comment]
@Aniq55 close this buddy.
