### ISSUE TITLE
Reset button in pause screen

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#134]
Reset button in pause screen does not work.

**Comment by vineetjc** [comment]
I believe this issue is irrelevant now. Reset button seems to be working fine. I guess it's with reference to the pending pull request on there by @CaptainDaVinci  ? I'm not aware as to why it was reopened some days back, but otherwise, we could go ahead and close this too.

**Comment by thealphadollar** [comment]
It is still not working, I'm doing this now.
