### ISSUE TITLE
Make the puck and paddle circles of almost same size.

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#16]
Increase the radius of the puck
Use concentric circles for the paddle

**Comment by Aniq55** [comment]
Assigned to @nityanandagohain

**Comment by Aniq55** [comment]
@nityanandagohain this is very important. Please do this, before moving on to other issues.

**Comment by nityanandagohain** [comment]
Ok @Aniq55

**Comment by nityanandagohain** [comment]
@Aniq55 submitted pr #49
