### ISSUE TITLE
Option to add Player Names

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#161]
In the start screen, allow users to add their names, just under the select color option.
Also, display these entered names instead of Score1 and Score2.
If a player name is not entered. simply write Player 1 and Player 2 instead of Score1 and Score2

**Comment by thealphadollar** [comment]
On it!

**Comment by Aniq55** [comment]
@thealphadollar also update the screenshots in the README when you open a PR for this issue.
