### ISSUE TITLE
Add goals on either end and add Scoring system

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#18]
The goal width should be appropriate
Also, design and display the scoring system.
Refer to [Air Hockey Wiki](https://en.wikipedia.org/wiki/Air_hockey)

**Comment by Aniq55** [comment]
The puck should disappear into the goal

**Comment by soumam007** [comment]
I will like to work on this as well as on the scoring system. I went through the program code and i got the basic understanding of pygame, but i will be able to work on this after 30th ,is that ok?

**Comment by vineetjc** [comment]
I wish to work on this. It would be great if I am assigned to solving this issue.

**Comment by Aniq55** [comment]
Assigned to @soumam007 
Waitlist: @vineetjc 
Please try to do this by the first week of December.
