### ISSUE TITLE
If only one player changes name, changes not reflected for only that player

### ISSUE THREAD

**Issue by vineetjc** [NITDgpOS/AirHockey#186]
If only one player changes name and if by chance the other player box is left out, the game begins with all names reset to the default 'Player x' form.

**Comment by Aniq55** [comment]
If I change name of player one to X and leave the other player blank, what I get on the screen is `X` vs `   `

**Comment by vineetjc** [comment]
If Player 2 changes name to X and the other is left blank, what I get on the screen is Player 1 vs Player 2.

Either way, I have made sure that be it X vs blank or the above, I've corrected it.

**Comment by Aniq55** [comment]
Alright. Merging in a while
