### ISSUE TITLE
Keyboard selection for Easy and Hard not working

### ISSUE THREAD

**Issue by vineetjc** [NITDgpOS/AirHockey#187]
With new commits, the function was modified in startsScreen.py such that it unpacks more values than before. Error occurs on choosing mode using keyboard.

**Comment by Aniq55** [comment]
I just pulled the latest changes and checked the game. I didn't get any such error.

**Comment by vineetjc** [comment]
@Aniq55 Just to check again, I made a new local copy and tried it. It still shows me an error pressing 'e' or 'h'. I may be wrong. Why am I getting this?

**Comment by vineetjc** [comment]
Apologies, I might have sounded vague
