### ISSUE TITLE
Let the players select difficulty level

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#2]
Difficulty level is directly proportional to the velocity of the puck.

Slow puck : Easy
Fast puck: Difficult

**Comment by vineetjc** [comment]
Is this about creating an interface to choose the difficulty? And if there isn't a bot vs player mode yet, what does the difficulty indicate for the two players? I could work on this.

**Comment by Aniq55** [comment]
Assigned to @arpitmisraw

Everything is mentioned in the Issue description. This difficulty setting makes the game difficult for both players. Here is no question of Bot vs Player.
