### ISSUE TITLE
Error while starting game

### ISSUE THREAD

**Issue by ananyo2012** [NITDgpOS/AirHockey#22]
I am getting this error while starting the game
```
File "Air_hockey.py", line 101, in <module>
    pygame.draw.circle(screen, (255,255,255), (puck.x, puck.y), (puck.width/2))
TypeError: integer argument expected, got float
```
Refers to [line 101](https://github.com/Aniq55/AirHockey/blob/master/Air_hockey.py#L101). You should probably typecast it to an integer.

**Comment by Aniq55** [comment]
okay @ananyo2012

**Comment by ananyo2012** [comment]
Yup it gets solved by the typecast.
