### ISSUE TITLE
Correct impact between  puck and red bar

### ISSUE THREAD

**Issue by psushi** [NITDgpOS/AirHockey#29]
The impact between the puck and red bar is not perfect, it looks as if the puck is not touching , rather passing through the red bar.

**Comment by psushi** [comment]
This is my first time, i would like to work on this, if its beginner friendly. :)

**Comment by Aniq55** [comment]
Assigned to @SusheendharVijay
PS. Solve this issue before #16 is solved, otherwise this issue will become useless.
