### ISSUE TITLE
Add fullscreen support  

### ISSUE THREAD

**Issue by nityanandagohain** [NITDgpOS/AirHockey#31]
Add full screen support for this game to make it more immerse .

**Comment by Aniq55** [comment]
Hint: add a scaling factor, to scale all up all in-game dimensions

**Comment by vineetjc** [comment]
I would like to work on this. @Aniq55 I could make this as a toggle option for the user.

**Comment by thealphadollar** [comment]
@Aniq55 I would also like to work on this.

**Comment by Aniq55** [comment]
Assigned to @thealphadollar

**Comment by CaptainDaVinci** [comment]
Will you be adding screen resizing option or just two sizes: normal and full screen?

**Comment by thealphadollar** [comment]
I'm looking forward to learn adding resizing. I'll first though make the game just fullscreen.
