### ISSUE TITLE
Introducing power-ups in the game

### ISSUE THREAD

**Issue by suhas919** [NITDgpOS/AirHockey#32]
Power-ups appear in the game at random timings, the player has to touch it with their paddle to activate it. Some possible features are:
* Bonus points
* Slowing the puck on their side for 5 seconds
* decreasing the size of the goal in their area
* increasing the length of the paddle

The power-ups may also appear non-randomly, based on the performance of the player. suppose, consecutive 3 goals by one player shows a power-up.

**Comment by Aniq55** [comment]
Assigned to @Kitwradr 

one slot remaining.

**Comment by psushi** [comment]
I would like to help with this, @Kitwradr if you want to, please let me know if i can help in any way. thanks!

**Comment by vineetjc** [comment]
I would like to help with this in anyway

**Comment by Kitwradr** [comment]
Sure u can help as i am still a beginner

**Comment by suhas919** [comment]
Sure you guys can help as i am still a beginner

**Comment by psushi** [comment]
Cool :) , so once you're done with the basic framework, can I help with the second feature, the puck getting slowed, that seems like a good power-up.

**Comment by Aniq55** [comment]
@SusheendharVijay sure. All the changes are in the `powerups` branch. You may start contributing.
