### ISSUE TITLE
Puck interacting with Paddle on the shorter side or corner

### ISSUE THREAD

**Issue by IAnandKumar** [NITDgpOS/AirHockey#34]
![3](https://user-images.githubusercontent.com/25329833/33419323-bb35381e-d55e-11e7-8569-ff0a5441f26e.PNG)
![4](https://user-images.githubusercontent.com/25329833/33419324-bb96a1d0-d55e-11e7-9e9c-bc6fb731d6b2.PNG)
![5](https://user-images.githubusercontent.com/25329833/33419325-bbcdc35e-d55e-11e7-8180-5ffdeafb2cf9.PNG)
![1](https://user-images.githubusercontent.com/25329833/33419326-bc2ef8a4-d55e-11e7-820f-a4f78e49fd60.PNG)
![2](https://user-images.githubusercontent.com/25329833/33419327-bc8e9a16-d55e-11e7-8162-c4b230fe24dc.PNG)
These pics show the problem.

**Comment by IAnandKumar** [comment]
The correct order is 4,5,1,2,3.

**Comment by Aniq55** [comment]
Assigned to @IAnandKumar
