### ISSUE TITLE
Puck bounce off at an angle on colliding

### ISSUE THREAD

**Issue by CaptainDaVinci** [NITDgpOS/AirHockey#39]
Depending of the portion of the paddle the puck collides, it should bounce off at an angle, something like this:
![pong](https://user-images.githubusercontent.com/21019116/33454021-81ad0a10-d63d-11e7-8578-80b265f65bbd.png)

**Comment by Aniq55** [comment]
Assigned to @CaptainDaVinci

**Comment by Aniq55** [comment]
The paddle is now circular, this change is not inapplicable  I feel. @CaptainDaVinci

**Comment by CaptainDaVinci** [comment]
Yes, you may close this.
