### ISSUE TITLE
Update screenshot in readme

### ISSUE THREAD

**Issue by abh3po** [NITDgpOS/AirHockey#41]

**Comment by Aniq55** [comment]
@soumam007

**Comment by soumam007** [comment]
done  :+1: @abhsag24 @Aniq55

**Comment by vchrombie** [comment]
Is there anything still pending with this issue?
Can I help you with it?

**Comment by Aniq55** [comment]
@vchrombie yes. sure. Run the game and update the screenshot

**Comment by vchrombie** [comment]
Okay
I will do it.

Do I need to remove the old one?

**Comment by abh3po** [comment]
@vchrombie yup

**Comment by Aniq55** [comment]
Include:
* start screen 
* main game screen

**Comment by vchrombie** [comment]
Okay
I will do that.

**Comment by thealphadollar** [comment]
This issue can be closed till we have another screen to add.

**Comment by Aniq55** [comment]
Now there's a change in the start screen which can be updated

**Comment by Aniq55** [comment]
Now there's a change in the start screen, so the screenshot can be updated

**Comment by vchrombie** [comment]
Can I do that?

I also have a new logo.
Can I send a PR for that also?

**Comment by Aniq55** [comment]
send the logo in the Gitter channel first. @vchrombie
