### ISSUE TITLE
Make game run with click on an executable [ubuntu]

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#43]
Make an executable that'll run the game without the need to open terminal.

**Comment by CaptainDaVinci** [comment]
I have tried `pyinstaller` to package the application in one folder, but application keeps crashing and I am not sure how I can debug this, I tried logging to the console but that didn't work either.

P.S: application builds successfully

**Comment by Aniq55** [comment]
@CaptainDaVinci see this https://askubuntu.com/questions/141229/how-to-add-a-shell-script-to-launcher-as-shortcut

**Comment by CaptainDaVinci** [comment]
But that would work only for Linux, right?

I managed to package the application using `pyinstaller` for Linux, using the same spec file we can package for Windows as well. Where exactly do you plan to host the bundle?

**Comment by Aniq55** [comment]
Till now no plans of hosting. Let's get version 1 ready, then we can think. Solve this for Linux and later issue will be there for windows. @CaptainDaVinci
