### ISSUE TITLE
Create a Start Game Screen

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#5]
Create a start game page, which says "Press Enter to start game" and then start game.

**Comment by Aniq55** [comment]
Assigned to @nityanandagohain

**Comment by Aniq55** [comment]
@nityanandagohain do #6 and #5 together. Let the players choose their paddle colors on the start screen.

**Comment by nityanandagohain** [comment]
Ok  @Aniq55 .
