### ISSUE TITLE
Bounce off walls

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#54]
The ball should bounce off all walls, even the ones which are vertical.

**Comment by thealphadollar** [comment]
Please assign this to me.

**Comment by Aniq55** [comment]
@thealphadollar make sure the puck doesn't bounce off when it touches the goals on either side. This collision with the goals will be later used for calculating scores.

**Comment by soumam007** [comment]
wait i was doing that check issue #18    .Adding the scoring system had that as a sub part , sorry @thealphadollar
