### ISSUE TITLE
Puck-Paddle collision not perfect.

### ISSUE THREAD

**Issue by CaptainDaVinci** [NITDgpOS/AirHockey#56]
At slow speeds we can observe that the collisions are imperfect and unnatural.

**Comment by Aniq55** [comment]
In case of collision of two circular discs (paddle and puck here), if it is head-on, then the direction of the puck will be completely reversed. Are we on the same page @CaptainDaVinci ?

**Comment by CaptainDaVinci** [comment]
Yes.

**Comment by soumam007** [comment]
And moreover i will like to add the fact, whenever there is a collision between the backside of the paddle with the puck then also its not changing the velocity , be the puck is moving slowly or fast.

The same is the case on hitting on the left and right side, only front headto head collision is working fine 


@CaptainDaVinci 
@Aniq55
