### ISSUE TITLE
Upon Reset Puck should go randomly

### ISSUE THREAD

**Issue by Lasers67** [NITDgpOS/AirHockey#59]
When reset the Puck sets off in only a specific direction based of who loses, it should be more random

**Comment by thealphadollar** [comment]
@Aniq55 Me on this please.

**Comment by Aniq55** [comment]
@Lasers67 shall I assign this to @thealphadollar ?

**Comment by psushi** [comment]
can I help with this?
and I think rather being random, it can start from the side of the player who just lost the point, what do you think?

**Comment by Aniq55** [comment]
@SusheendharVijay by random we mean the angle of launch. This issue was created by @Lasers67 so he has the right to either solve it himself or assign it to someone else.

**Comment by pani-vishal** [comment]
Can I work on it?:-)

**Comment by Lasers67** [comment]
Yes u can assign it to @thealphadollar

**Comment by Aniq55** [comment]
Assigned to @thealphadollar
