### ISSUE TITLE
Using time limit for each round

### ISSUE THREAD

**Issue by soumam007** [NITDgpOS/AirHockey#62]
if there will be three rounds ,use constant time limit for each round, because :--
1> global best points will remain open ended,hence can be updated with the score
2> I gotta think of more reasons

I can work on this even @Aniq55

**Comment by Aniq55** [comment]
Solve with #9

**Comment by thealphadollar** [comment]
@Aniq55 is this required?
Edit: I'll say we don't need a timer since the game is already short.
