### ISSUE TITLE
Enhance the README

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#7]

**Comment by vineetjc** [comment]
What are the specifications of this? Any particular way to go by what you meant as 'enhancing'?

**Comment by Aniq55** [comment]
@vineetjc You can add a gif to show how the game is working.
Provide documentation to the code, explaining each object and function in detail.

This issue will not be assigned to anyone and people can send in whatever they want. It is up to me to review it.

**Comment by soumam007** [comment]
@vineetjc  are you still working on it ?

**Comment by vchrombie** [comment]
Can I add some badges to the README.md?

like..
[![chat on Slack](https://img.shields.io/badge/chat-Slack-blue.svg)](#)

**Comment by Aniq55** [comment]
We don't have a Slack channel. So doesn't make sense. @vchrombie

**Comment by vchrombie** [comment]
It can be modified.
Slack was just an example.

gitter link can also be uploaded.
[![chat on Slack](https://img.shields.io/badge/chat-Gitter-blue.svg)](#)
another one..
[![made with &hearts in Python](https://img.shields.io/badge/made%20with%20%E2%9D%A4%20in-Python-red.svg)](#)
