### ISSUE TITLE
Using Images for background, puck and paddle.

### ISSUE THREAD

**Issue by CaptainDaVinci** [NITDgpOS/AirHockey#77]

**Comment by Aniq55** [comment]
images will make it slower IMO, why not use material design color to make the overall design look sharper?

**Comment by CaptainDaVinci** [comment]
Would the performance impact be drastic? Hard coding the design would be tedious.

**Comment by Aniq55** [comment]
Before woring on this, post the textures/pictures here. @CaptainDaVinci

**Comment by CaptainDaVinci** [comment]
I haven't created one, but it would be similar to this: 

![bg](https://user-images.githubusercontent.com/21019116/33575636-4f91ecca-d963-11e7-9bcf-e59c1299dc9e.png)

**Comment by thealphadollar** [comment]
Well, this would make it harder to resize the window keeping the quality of the images same.

**Comment by CaptainDaVinci** [comment]
We could keep just two screen sizes and create two different sized sketches.

**Comment by Aniq55** [comment]
@thealphadollar I don't really support the Full-screen issue.

**Comment by thealphadollar** [comment]
@Aniq55 I can agree to that, we've other features to implement before fullscreen. Let's keep that on list though.

**Comment by thealphadollar** [comment]
@CaptainDaVinci Every screen can have different resolution and hence full screen will have different dimensions.

**Comment by thealphadollar** [comment]
@Aniq55  This can be closed as the current puck and paddle fit the scene pretty well. Also, the background isn't required.
Implementing this will require scrapping off features like paddle color and theme.
