### ISSUE TITLE
Add function to serve the puck

### ISSUE THREAD

**Issue by thealphadollar** [NITDgpOS/AirHockey#82]
Whenever a goal happens, the player who loses should be able to decide the position of the puck and then hit it according to himself.

**Comment by Lasers67** [comment]
Can i work on this @thealphadollar ??

**Comment by thealphadollar** [comment]
@Lasers67 Your call then :+1:

**Comment by Lasers67** [comment]
@Aniq55 can you give this issue assigned label?

**Comment by Aniq55** [comment]
Assigned to @Lasers67
