### ISSUE TITLE
Make each game of three rounds

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/AirHockey#9]
Make each game of three rounds and declare the winner at the end of the game

**Comment by vineetjc** [comment]
I wish to work on this. It would be great if I am assigned to solving this issue.

**Comment by Lasers67** [comment]
I would also be privileged to work on this as well as displaying score on the screen as well as displaying a timer which would indicate the end of the round or maybe some x number of goals

**Comment by Aniq55** [comment]
Assigned to @Lasers67 
Do this after #18 is solved.

**Comment by thealphadollar** [comment]
@Aniq55 this has been taken care of I guess and should be closed.
