### ISSUE TITLE
Incorrect score updates

### ISSUE THREAD

**Issue by CaptainDaVinci** [NITDgpOS/AirHockey#96]
When yellow misses its score is incremented, is this intentional?

**Comment by Aniq55** [comment]
No, the scores are mismatched. @CaptainDaVinci

**Comment by thealphadollar** [comment]
I'll do this.

**Comment by thealphadollar** [comment]
@Aniq55 Please close this issue.

**Comment by thealphadollar** [comment]
!CLOSED
